default_platform(:android)

platform :android do
  desc "Upload the release app bundle and store metadata to the internal track"
  lane :internal do
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      metadata_path: "fastlane/metadata/android",
      skip_upload_apk: true,
      skip_upload_aab: false,
      skip_upload_metadata: false,
      skip_upload_changelogs: false,
      skip_upload_images: false,
      skip_upload_screenshots: false
    )
  end
end
